#都道府県をキー、地方を値とする辞書が定義してある
REGION = {
	"hokkaido":"HOKKAIDO TOHOKU",
	"aomori":"HOKKAIDO TOHOKU",
	"iwate":"HOKKAIDO TOHOKU",
	"akita":"HOKKAIDO TOHOKU",
	"miyagi":"HOKKAIDO TOHOKU",
	"fukusima":"HOKKAIDO TOHOKU",
	"yamagata":"HOKKAIDO TOHOKU",
	"ibaraki":"KANTO",
	"gunma":"KANTO",
	"totigi":"KANTO",
	"saitama":"KANTO",
	"chiba":"KANTO",
	"toukyou":"KANTO",
	"kanagawa":"KANTO",
	"shizuoka":"chubu",
	"aichi":"chubu",
	"gifu":"chubu",
	"nagano":"chubu",
	"yamanashi":"chubu",
	"ishikawa":"HOKURIKU KOUSHINETSU",
	"niigata":"HOKURIKU KOUSHINETSU",
	"toyama":"HOKURIKU KOUSHINETSU",
	"fukui":"HOKURIKU KOUSHINETSU",
	"mie":"KINKI",
	"shiga":"KINKI",
	"kyoto":"KINKI,",
	"osaka":"KINKI",
	"hyogo":"KINKI",
	"wakayama":"KINKI",
	"nara":"KINKI",
	"tottori":"CHUGOKU SHIKOKU",
	"shimane":"CHUGOKU SHIKOKU",
	"hiroshima":"CHUGOKU SHIKOKU",
	"okayama":"CHUGOKU SHIKOKU",
	"yamaguchi":"CHUGOKU SHIKOKU",
	"kagawa":"CHUGOKU SHIKOKU",
	"kochi":"CHUGOKU SHIKOKU",
	"ehime":"CHUGOKU SHIKOKU",
	"tokushima":"CHUGOKU SHIKOKU",
	"fukuoka":"KYUSHU",
	"oita":"KYUSHU",
	"saga":"KYUSHU",
	"nagasaki":"KYUSHU",
	"miyazaki":"KYUSHU",
	"kagoshima":"KYUSHU",
	"okinawa":"KYUSHU",
	"zenkoku":"ZENKOKU"
}
